# English translations for TGraph Bot
# Copyright (C) 2025 engels74
# This file is distributed under the same license as the TGraph Bot package.
# engels74 <141435164+engels74@users.noreply.github.com>, 2025.
#
msgid ""
msgstr ""
"Project-Id-Version: TGraph Bot 1.0.0\n"
"Report-Msgid-Bugs-To: https://github.com/engels74/tgraph-bot-source/issues\n"
"POT-Creation-Date: 2025-06-19 20:31\n"
"PO-Revision-Date: 2025-06-19 20:31\n"
"Last-Translator: engels74 <141435164+engels74@users.noreply.github.com>\n"
"Language-Team: English <https://hosted.weblate.org/projects/tgraph-bot/tgraph-bot/en/\n"
"Language: en\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: Weblate 5.0\n"

#: utils/error_handler.py:308
msgid "An error occurred while processing your request"
msgstr "An error occurred while processing your request"

#: tests/unit/test_i18n.py:113
#: tests/integration/test_locale_structure.py:133
#: tests/integration/test_locale_structure.py:144
#: tests/integration/test_locale_structure.py:155
msgid "Bot is online and ready!"
msgstr "Bot is online and ready!"

#: tests/unit/test_i18n.py:45
msgid "Hello, world!"
msgstr "Hello, world!"

#: tests/unit/test_i18n.py:86
msgid "Hello, {invalid_key}"
msgstr "Hello, {invalid_key}"

#: tests/unit/test_i18n.py:52
#: tests/unit/test_i18n.py:58
msgid "Hello, {name}!"
msgstr "Hello, {name}!"

#: bot/commands/about.py:54
msgid "TGraph Bot"
msgstr "TGraph Bot"

#: bot/commands/about.py:55
msgid "TGraph Bot - Tautulli Discord Graph Generator"
msgstr "TGraph Bot - Tautulli Discord Graph Generator"

#: tests/unit/test_i18n.py:63
#: tests/unit/test_i18n.py:124
msgid "Test message"
msgstr "Test message"

#: tests/unit/test_i18n.py:150
msgid "Test string"
msgstr "Test string"

#: utils/error_handler.py:302
msgid "The external service is temporarily unavailable. Please try again later."
msgstr "The external service is temporarily unavailable. Please try again later."

#: utils/error_handler.py:304
msgid "The provided input is invalid. Please check your parameters and try again."
msgstr "The provided input is invalid. Please check your parameters and try again."

#: utils/error_handler.py:306
msgid "The server is experiencing resource constraints. Please try again later."
msgstr "The server is experiencing resource constraints. Please try again later."

#: utils/error_handler.py:301
msgid "There was a network connectivity issue. Please try again in a moment."
msgstr "There was a network connectivity issue. Please try again in a moment."

#: utils/error_handler.py:307
msgid "There was an issue communicating with Discord. Please try again."
msgstr "There was an issue communicating with Discord. Please try again."

#: utils/error_handler.py:305
msgid "There's a configuration issue. Please contact the server administrators."
msgstr "There's a configuration issue. Please contact the server administrators."

#: tests/unit/test_i18n.py:69
msgid "User {user} has {count} items"
msgstr "User {user} has {count} items"

#: tests/unit/test_i18n.py:220
msgid "User {user} has {n} message"
msgstr "User {user} has {n} message"

#: tests/unit/test_i18n.py:220
msgid "User {user} has {n} messages"
msgstr "User {user} has {n} messages"

#: utils/error_handler.py:303
msgid "You don't have permission to perform this action."
msgstr "You don't have permission to perform this action."

#: tests/unit/test_i18n.py:230
msgid "You have {n} item"
msgstr "You have {n} item"

#: tests/unit/test_i18n.py:230
msgid "You have {n} items"
msgstr "You have {n} items"

#: tests/unit/test_i18n.py:210
#: tests/unit/test_i18n.py:215
msgid "You have {n} message"
msgstr "You have {n} message"

#: tests/unit/test_i18n.py:210
#: tests/unit/test_i18n.py:215
msgid "You have {n} messages"
msgstr "You have {n} messages"

